"""Remove extra fields

Revision ID: 1c1cffbc9d56
Revises: 60e3dbe41547
Create Date: 2022-12-28 15:27:20.151546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c1cffbc9d56'
down_revision = '60e3dbe41547'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('period', 'is_online')
    op.drop_column('period', 'duration')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('period', sa.Column('duration', sa.INTEGER(), nullable=False))
    op.add_column('period', sa.Column('is_online', sa.BOOLEAN(), nullable=False))
    # ### end Alembic commands ###
