"""Remove exxtra fields from period

Revision ID: 346de00c522c
Revises: 60e3dbe41547
Create Date: 2022-12-28 15:13:29.324368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '346de00c522c'
down_revision = '60e3dbe41547'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('period', 'duration')
    op.drop_column('period', 'is_online')
    op.drop_column('period', 'zone_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('period', sa.Column('zone_id', sa.INTEGER(), nullable=False))
    op.add_column('period', sa.Column('is_online', sa.BOOLEAN(), nullable=False))
    op.add_column('period', sa.Column('duration', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###
