"""Add statistics model

Revision ID: 54742c908ca0
Revises: 1c1cffbc9d56
Create Date: 2022-12-30 01:48:03.854989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54742c908ca0'
down_revision = '1c1cffbc9d56'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statistics',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('z1_duration', sa.Interval(), nullable=False),
    sa.Column('z2_duration', sa.Interval(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('statistics')
    # ### end Alembic commands ###
