name: Build image, Push to Dockerhub, Rebuild and run container

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/inquisitor:latest
      NETWORK: pk_prod-network
      CONTAINER: bot

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ${{ env.IMAGE }} .

      - name: Push Docker image to Docker Hub
        run: docker push ${{ env.IMAGE }}

      - name: ssh connect and restart container
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd ${{ vars.HOME_PATH }}
            
            docker pull ${{ env.IMAGE }}
            docker stop ${{ env.CONTAINER }}
            docker rm ${{ env.CONTAINER }}
            script: |
            cd ${{ vars.HOME_PATH }}
            
            docker pull ${{ env.IMAGE }}
            docker stop ${{ env.CONTAINER }}
            docker rm ${{ env.CONTAINER }}
            docker run -d \
              --restart unless-stopped \
              --name ${{ env.CONTAINER }} \
              --network ${{ env.NETWORK }} \
              --env-file .env \
              -v /home/dudko/inquisitor/logs:/app/logs \
              ${{ env.IMAGE }}
            
            docker system prune -a -f --volumes
